const $=id=>document.getElementById(id);
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
const today=()=>new Date().toISOString().slice(0,10);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const norm=s=>String(s||'').trim().toUpperCase();
const clone=o=>JSON.parse(JSON.stringify(o));
const fmtDate=v=>{if(!v)return'-';const [y,m,d]=v.split('-');return y&&m&&d?`${d}/${m}/${y}`:v};
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);

const DEFAULT_PRICE_CONFIG={
  finishes:{
    'LINHO SINTÉTICO':{price:42,normalMax:280,specialMax:305,specialPct:10,rollWidth:3},
    'LINHO COMPOSTO 6%':{price:55,normalMax:300,specialMax:300,specialPct:0,rollWidth:3},
    'LINHO COMPOSTO 12%':{price:60,normalMax:300,specialMax:300,specialPct:0,rollWidth:3},
    'LINHO NACIONAL':{price:90,normalMax:300,specialMax:300,specialPct:0,rollWidth:3},
    'VOIL LISO':{price:27,normalMax:280,specialMax:280,specialPct:0,rollWidth:3},
    'VOIL SUPER':{price:32,normalMax:280,specialMax:280,specialPct:0,rollWidth:3},
    'VOIL TRABALHADO COMPOSTO':{price:42,normalMax:280,specialMax:280,specialPct:0,rollWidth:3}
  },
  linings:{
    'MICROFIBRA LEVE':{price:31,normalMax:300,rollWidth:3},
    'GABARDINE 70%':{price:45,normalMax:280,rollWidth:3},
    'BLACKOUT 100% LEVE':{price:65,normalMax:280,rollWidth:3},
    'BLACKOUT 100% PESADO':{price:85,normalMax:280,rollWidth:3}
  },
  pleatLabor:{'FRANZIDO':10,'WAVE':20,'SOBREPOSTO':20,'OUTRO':0},
  sliders:{finish:0.70,lining:0.65,spacingCm:5},
  sewingPerMeter:8,
  swiss:{tiers:[{m:1.5,p:48},{m:2,p:65},{m:2.5,p:97},{m:3,p:115},{m:3.5,p:130},{m:4,p:145},{m:4.5,p:160},{m:5,p:180},{m:5.5,p:190},{m:6,p:200}],clamp:7,end:7},
  wave:{rodPerMeter:35,support:38,end:0,maxSupportSpan:1.6},
  cordPct:35,
  motor:{basePerLeaf:2000,hardwarePct:15},
  install:[{maxH:3,price:60},{maxH:3.5,price:80},{maxH:4,price:180},{maxH:5,price:250},{maxH:6,price:300},{maxH:99,price:300}],
  terms:{cashDiscountPct:8,p18AddPct:14},
  commissionDefault:5
};
const DEFAULT_USERS=[
  {username:'VENDAS1',name:'Vendas 1',role:'sales',commission:5,builtIn:true},
  {username:'VENDAS2',name:'Vendas 2',role:'sales',commission:5,builtIn:true},
  {username:'GESTOR',name:'Gestor',role:'gestor',commission:0,builtIn:true},
  {username:'ERIC.DELGOBO',name:'Eric Luiz Delgobo',role:'gestor',commission:0,builtIn:true},
  {username:'LUIZ.SERGIO',name:'Luiz Sergio Delgobo',role:'gestor',commission:0,builtIn:true}
];
const STAGES=['RECEPÇÃO','CORTE','COSTURA','BARRA','PASSADORIA','EXPEDIÇÃO'];
const NAV=[
  ['quote','Novo orçamento','all'],['quotes','Orçamentos','all'],['clients','Clientes','sales'],['orders','Pedidos','all'],['production','Produção','production'],['install','Instalações','all'],['inventory','Estoque','gestor'],['pricing','Tabela / Preços','gestor'],['kpis','KPIs','gestor'],['payables','Contas a pagar','gestor'],['suppliers','Compras / Fornecedores','gestor'],['rework','Retrabalho','all'],['users','Usuários','gestor']
];
let token=sessionStorage.getItem('novaV8Token')||'';
let currentUser=JSON.parse(sessionStorage.getItem('novaV8User')||'null');
let db={quotes:[],orders:[],clients:[],users:[],disabledUsers:[],products:[],suppliers:[],payables:[],reworks:[],priceConfig:clone(DEFAULT_PRICE_CONFIG),settings:{}};
let draft={numero:null,client:'',date:today(),address:'',contact:'',seller:'',travel:0,environments:[]};
let editingClientId=null;

async function sha256(text){const data=new TextEncoder().encode(String(text));const digest=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function api(path,options={}){const r=await fetch('/api/'+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...(options.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Falha na comunicação com a nuvem.');return j}
function cloud(msg,warn=false){const e=$('cloudStatus');if(!e)return;e.textContent=msg;e.className='cloud'+(warn?' warn':'')}
function isGestor(){return currentUser?.role==='gestor'}
function isProduction(){return currentUser?.role==='production'}
function currentUsername(){return norm(currentUser?.username)}
function allUsers(){const disabled=new Set((db.disabledUsers||[]).map(norm));return [...DEFAULT_USERS,...(db.users||[])].filter((u,i,a)=>a.findIndex(x=>norm(x.username)===norm(u.username))===i).filter(u=>!disabled.has(norm(u.username)))}
function sellerName(username){return allUsers().find(u=>norm(u.username)===norm(username))?.name||username||'-'}
function sellerCommission(username){return Number(allUsers().find(u=>norm(u.username)===norm(username))?.commission ?? db.priceConfig.commissionDefault ??5)}
function canSeeQuote(q){return isGestor()||isProduction()||norm(q.ownerUser||q.seller)===currentUsername()}
function canSeeOrder(o){return isGestor()||isProduction()||norm(o.ownerUser||o.seller)===currentUsername()}
function mergeConfig(c){const base=clone(DEFAULT_PRICE_CONFIG);if(!c)return base;for(const k of Object.keys(c)){if(c[k]&&typeof c[k]==='object'&&!Array.isArray(c[k])&&base[k]&&typeof base[k]==='object'&&!Array.isArray(base[k]))base[k]={...base[k],...c[k]};else base[k]=c[k]}return base}
async function loadCloud(){try{cloud('Sincronizando...');const j=await api('data');db={...db,...j,priceConfig:mergeConfig(j.priceConfig)};cloud('Dados sincronizados na nuvem');renderAll()}catch(e){cloud('Sem conexão com a nuvem',true);alert(e.message)}}
let saveTimer=null;function queueSave(){clearTimeout(saveTimer);saveTimer=setTimeout(saveCloud,250)}
async function saveCloud(){if(!token)return;try{cloud('Salvando...');const j=await api('data',{method:'POST',body:JSON.stringify(db)});db.updatedAt=j.updatedAt;cloud('Dados salvos na nuvem')}catch(e){cloud('Falha ao salvar',true);alert('Não foi possível salvar: '+e.message)}}

function renderNav(){const nav=$('nav');nav.innerHTML='';for(const [id,label,access] of NAV){let show=true;if(access==='gestor')show=isGestor();if(access==='production')show=isGestor()||isProduction();if(access==='sales')show=!isProduction();if(!show)continue;const b=document.createElement('button');b.className='nav-btn'+(id==='quote'?' active':'');b.dataset.view=id;b.textContent=label;b.onclick=()=>setView(id);nav.appendChild(b)}}
function setView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active','print-target'));$('view-'+id)?.classList.add('active');document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='kpis')renderKpis();if(id==='pricing')renderPricing();}
function renderAll(){renderNav();renderQuote();renderQuotes();renderClients();renderOrders();renderProduction();renderInstall();renderProducts();renderPricing();renderKpis();renderPayables();renderSuppliers();renderReworks();renderUsers();}

function fillSelect(el,items,selected){el.innerHTML=items.map(x=>`<option ${x===selected?'selected':''}>${esc(x)}</option>`).join('')}
function setupSelectors(){fillSelect($('eFinish'),Object.keys(db.priceConfig.finishes));fillSelect($('eLining'),Object.keys(db.priceConfig.linings));fillSelect($('eFinishColor'),['BRANCO','OFF WHITE','MARFIM','BEGE','AREIA','TRIGO','CINZA','PRATA','OUTRO']);fillSelect($('eLiningColor'),['CINZA','MARFIM','BRANCO','AREIA','OUTRO']);fillSelect($('eFinishPleat'),['FRANZIDO','WAVE','SOBREPOSTO','OUTRO'],'WAVE');fillSelect($('eLiningPleat'),['FRANZIDO','WAVE','SOBREPOSTO','OUTRO'],'FRANZIDO');fillSelect($('eFinishGather'),['1.5','2.0','2.5','3.0','3.5','4.0'],'3.0');fillSelect($('eLiningGather'),['1.5','2.0','2.5','3.0','3.5','4.0'],'2.0');fillSelect($('eFixation'),['TRILHO SUÍÇO','VARÃO WAVE','VARÃO WAVE COM COMANDO POR CORDA','TRILHO MOTORIZADO']);fillSelect($('eFixColor'),['BRANCO','PRETO','CROMADO','ESCOVADO','OURO VELHO','DOURADO']);updateModelFields()}
function updateModelFields(){const m=$('eModel').value;document.querySelectorAll('.finish-field').forEach(x=>x.classList.toggle('hidden',m==='LINING'));document.querySelectorAll('.lining-field').forEach(x=>x.classList.toggle('hidden',m==='FINISH'));document.querySelectorAll('.choice').forEach(x=>x.classList.toggle('active',x.dataset.model===m));updatePreview()}
function fabricCalc(type,name,widthM,heightM,gather){const cfg=type==='finish'?db.priceConfig.finishes[name]:db.priceConfig.linings[name];if(!cfg)return null;const gathered=widthM*Number(gather);const hCm=heightM*100;let mode='LARGURA',panels=0,cutLength=0,consumption=gathered,pricePct=0;const normalMax=Number(cfg.normalMax||300),specialMax=Number(cfg.specialMax||normalMax);if(type==='finish'&&hCm>normalMax&&hCm<=specialMax){pricePct=Number(cfg.specialPct||0)}else if(hCm>specialMax){mode='ALTURA';cutLength=heightM+0.10+(heightM*0.10);panels=Math.ceil(gathered/Number(cfg.rollWidth||3));consumption=panels*cutLength}return {name,gathered,mode,panels,cutLength,consumption,unitPrice:Number(cfg.price||0)*(1+pricePct/100),pricePct,cost:consumption*Number(cfg.price||0)*(1+pricePct/100)}}
function fixationCalc(kind,widthM,model,leaves){const c=db.priceConfig;if(kind==='TRILHO SUÍÇO'){const rounded=Math.max(1.5,Math.ceil(widthM*2)/2);const tier=(c.swiss.tiers||[]).find(t=>rounded<=Number(t.m))||c.swiss.tiers[c.swiss.tiers.length-1];const clamps=Math.ceil(rounded/0.5);const ends=2;const base=Number(tier?.p||0)+clamps*Number(c.swiss.clamp||0)+ends*Number(c.swiss.end||0);return {kind,meters:rounded,clamps,ends,hardwareBase:base,total:base,detail:`${rounded.toFixed(1)}m • ${clamps} garras • ${ends} acabamentos`}}
  const multiplier=model==='COMPLETE'?2:1;const rodMeters=widthM*multiplier;const supports=Math.max(2,Math.ceil(widthM/Number(c.wave.maxSupportSpan||1.6)));const ends=model==='COMPLETE'?4:2;const base=rodMeters*Number(c.wave.rodPerMeter||0)+supports*Number(c.wave.support||0)+ends*Number(c.wave.end||0);let total=base;if(kind.includes('COMANDO'))total=base*(1+Number(c.cordPct||0)/100);if(kind==='TRILHO MOTORIZADO')total=base*(1+Number(c.motor.hardwarePct||0)/100)+Number(c.motor.basePerLeaf||0)*Number(leaves||1);return {kind,meters:rodMeters,supports,ends,hardwareBase:base,total,detail:`${rodMeters.toFixed(2)}m • ${supports} suportes • ${ends} tampas`}}
function installPrice(heightM){const tier=(db.priceConfig.install||[]).find(x=>heightM<=Number(x.maxH));return Number(tier?.price||0)}
function calcEnvironment(e){const w=Number(e.width)/100,h=Number(e.height)/100,leaves=Number(e.leaves||1);if(!w||!h)return null;const finish=e.model!=='LINING'?fabricCalc('finish',e.finish,w,h,e.finishGather):null;const lining=e.model!=='FINISH'?fabricCalc('lining',e.lining,w,h,e.liningGather):null;const layers=[finish,lining].filter(Boolean).length;const lateral=h*2*leaves*layers;const bars=(finish?.gathered||0)+(lining?.gathered||0);const sewingMeters=lateral+bars;const sewingCost=sewingMeters*Number(db.priceConfig.sewingPerMeter||0);const finishPleat=finish?finish.consumption*Number(db.priceConfig.pleatLabor[e.finishPleat]||0):0;const liningPleat=lining?lining.consumption*Number(db.priceConfig.pleatLabor[e.liningPleat]||0):0;const customPleat=Number(e.customPleat||0);const sliderQtyPerLayer=Math.ceil(Number(e.width)/Number(db.priceConfig.sliders.spacingCm||5));const finishSliders=finish?sliderQtyPerLayer:0,liningSliders=lining?sliderQtyPerLayer:0;const sliderCost=finishSliders*Number(db.priceConfig.sliders.finish||0)+liningSliders*Number(db.priceConfig.sliders.lining||0);const fixation=fixationCalc(e.fixation,w,e.model,leaves);const install=installPrice(h);const laborTotal=sewingCost+finishPleat+liningPleat+customPleat+install;const base4=(finish?.cost||0)+(lining?.cost||0)+sliderCost+fixation.total+laborTotal;const p18=base4*(1+Number(db.priceConfig.terms.p18AddPct||0)/100);const cash=base4*(1-Number(db.priceConfig.terms.cashDiscountPct||0)/100);return {...e,finishCalc:finish,liningCalc:lining,lateral,bars,sewingMeters,sewingCost,finishPleat,liningPleat,sliderQtyPerLayer,finishSliders,liningSliders,sliderCost,fixationCalc:fixation,installCost:install,laborTotal,base4,p18,cash,alerts:[finish?.mode==='ALTURA'?'ACABAMENTO POR ALTURA':'',lining?.mode==='ALTURA'?'FORRO POR ALTURA':'',finish?.pricePct?`LINHO SINTÉTICO +${finish.pricePct}%`:'' ].filter(Boolean)}}
function envFromForm(){return {id:uid(),name:$('eName').value.trim(),width:Number($('eWidth').value),height:Number($('eHeight').value),leaves:Number($('eLeaves').value),model:$('eModel').value,finish:$('eFinish').value,finishColor:$('eFinishColor').value,finishPleat:$('eFinishPleat').value,finishGather:$('eFinishGather').value,lining:$('eLining').value,liningColor:$('eLiningColor').value,liningPleat:$('eLiningPleat').value,liningGather:$('eLiningGather').value,fixation:$('eFixation').value,fixColor:$('eFixColor').value,customPleat:Number($('eCustomPleat').value||0),notes:$('eNotes').value.trim()}}
function updatePreview(){const e=envFromForm();if(!e.name||!e.width||!e.height){$('calcPreview').innerHTML='Preencha ambiente, medidas e configuração para visualizar o cálculo.';return}const c=calcEnvironment(e);if(!c)return;const f=c.finishCalc,l=c.liningCalc;$('calcPreview').innerHTML=`<strong>${esc(e.name)}</strong>${c.alerts.length?` <span class="badge warn">${esc(c.alerts.join(' • '))}</span>`:''}<div class="detail-list"><div class="detail-item"><span>Acabamento</span><strong>${f?`${f.consumption.toFixed(2)}m • ${money(f.cost)}`:'—'}</strong></div><div class="detail-item"><span>Forro</span><strong>${l?`${l.consumption.toFixed(2)}m • ${money(l.cost)}`:'—'}</strong></div><div class="detail-item"><span>Costura</span><strong>${c.sewingMeters.toFixed(2)}m • ${money(c.sewingCost)}</strong></div><div class="detail-item"><span>Deslizantes</span><strong>${c.finishSliders+c.liningSliders} un • ${money(c.sliderCost)}</strong></div><div class="detail-item"><span>Fixação</span><strong>${money(c.fixationCalc.total)}</strong></div><div class="detail-item"><span>Mão de obra total</span><strong>${money(c.laborTotal)}</strong></div></div><div class="price-strip"><div class="price-box"><span>18x</span><strong>${money(c.p18)}</strong></div><div class="price-box"><span>4x</span><strong>${money(c.base4)}</strong></div><div class="price-box"><span>À vista</span><strong>${money(c.cash)}</strong></div><div class="price-box"><span>Fixação</span><strong>${esc(c.fixationCalc.detail)}</strong></div></div>`}
function clearEnv(){['eName','eWidth','eHeight','eNotes'].forEach(id=>$(id).value='');$('eCustomPleat').value=0;updatePreview()}
function renderQuote(){if(!draft.numero)draft.numero=nextQuoteNumber();$('qClient').value=draft.client||'';$('qDate').value=draft.date||today();$('qAddress').value=draft.address||'';$('qContact').value=draft.contact||'';$('qSeller').value=draft.seller||(currentUser?.role==='sales'?sellerName(currentUser.username):sellerName(currentUser?.username));$('qSeller').readOnly=currentUser?.role==='sales';$('qTravel').value=draft.travel||0;const tbody=$('envTable');tbody.innerHTML='';let s18=0,s4=0,sc=0,sl=0;for(const e of draft.environments){const c=calcEnvironment(e);if(!c)continue;s18+=c.p18;s4+=c.base4;sc+=c.cash;sl+=c.laborTotal;const tr=document.createElement('tr');tr.innerHTML=`<td><strong>${esc(e.name)}</strong>${c.alerts.length?`<br><span class="badge warn">${esc(c.alerts.join(' • '))}</span>`:''}</td><td>${e.width} × ${e.height} cm<br>${e.leaves} folha(s)</td><td>${e.model==='COMPLETE'?'Cortina completa':e.model==='LINING'?'Apenas forro':'Apenas acabamento'}</td><td>${c.finishCalc?`${esc(e.finish)}<br>${esc(e.finishColor)} • ${e.finishPleat} ${e.finishGather}:1`:'—'}</td><td>${c.liningCalc?`${esc(e.lining)}<br>${esc(e.liningColor)} • ${e.liningPleat} ${e.liningGather}:1`:'—'}</td><td>${esc(e.fixation)}<br>${esc(e.fixColor)}</td><td>${money(c.laborTotal)}</td><td>${money(c.p18)}</td><td>${money(c.base4)}</td><td>${money(c.cash)}</td><td class="no-print"><button class="btn danger" data-del-env="${e.id}">Excluir</button></td>`;tbody.appendChild(tr)}const travel=Number($('qTravel')?.value||draft.travel||0);s18+=travel*(1+db.priceConfig.terms.p18AddPct/100);s4+=travel;sc+=travel*(1-db.priceConfig.terms.cashDiscountPct/100);$('qCount').textContent=draft.environments.length;$('q18').textContent=money(s18);$('q4').textContent=money(s4);$('qCash').textContent=money(sc);$('sumLabor').textContent=money(sl);$('sum18').textContent=money(s18);$('sum4').textContent=money(s4);$('sumCash').textContent=money(sc);document.querySelectorAll('[data-del-env]').forEach(b=>b.onclick=()=>{draft.environments=draft.environments.filter(x=>x.id!==b.dataset.delEnv);renderQuote()})}
function syncDraft(){draft.client=$('qClient').value.trim();draft.date=$('qDate').value;draft.address=$('qAddress').value.trim();draft.contact=$('qContact').value.trim();draft.seller=$('qSeller').value.trim();draft.travel=Number($('qTravel').value||0)}
function quoteTotals(q){let p18=0,p4=0,cash=0,labor=0;for(const e of q.environments||[]){const c=calcEnvironment(e);if(c){p18+=c.p18;p4+=c.base4;cash+=c.cash;labor+=c.laborTotal}}const t=Number(q.travel||0);p18+=t*(1+db.priceConfig.terms.p18AddPct/100);p4+=t;cash+=t*(1-db.priceConfig.terms.cashDiscountPct/100);return {p18,p4,cash,labor}}
function nextQuoteNumber(){return Math.max(1007,...db.quotes.map(x=>Number(x.numero)||0))+1}function nextOrderNumber(){return Math.max(5000,...db.orders.map(x=>Number(x.numero)||0))+1}
function saveQuote(print=false){syncDraft();if(!draft.client)return alert('Informe o cliente.');if(!draft.environments.length)return alert('Adicione pelo menos um ambiente.');const existing=db.quotes.findIndex(q=>Number(q.numero)===Number(draft.numero));const q={...clone(draft),ownerUser:currentUsername(),seller:draft.seller||sellerName(currentUser?.username),createdAt:existing>=0?db.quotes[existing].createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),status:db.quotes[existing]?.status||'ORÇAMENTO'};if(existing>=0)db.quotes[existing]=q;else db.quotes.unshift(q);upsertClientFromQuote(q);queueSave();renderAll();$('quoteStatus').textContent=`Orçamento ${String(q.numero).padStart(6,'0')} salvo.`;if(print)printQuote(q,'summary')}
function resetQuote(){if(!confirm('Zerar todos os dados do orçamento atual?'))return;draft={numero:nextQuoteNumber(),client:'',date:today(),address:'',contact:'',seller:currentUser?.role==='sales'?sellerName(currentUser.username):sellerName(currentUser?.username),travel:0,environments:[]};renderQuote();clearEnv()}
function upsertClientFromQuote(q){const key=norm(q.client);let c=db.clients.find(x=>norm(x.name)===key);if(c){c.address=q.address;c.contact=q.contact;c.lastSeller=q.seller;c.updatedAt=new Date().toISOString()}else db.clients.unshift({id:uid(),name:q.client,address:q.address,contact:q.contact,lastSeller:q.seller,createdAt:new Date().toISOString()})}
function printQuote(q,type='summary'){draft=clone(q);renderQuote();$('printQuoteTitle').textContent=`ORÇAMENTO Nº ${String(q.numero).padStart(6,'0')} • ${type==='detail'?'DETALHADO':'RESUMIDO'}`;if(type==='detail')document.querySelectorAll('#envTable tr').forEach((tr,i)=>{const e=q.environments[i],c=e&&calcEnvironment(e);if(!c)return;const td=tr.cells[0];td.innerHTML+=`<div class="print-only" style="margin-top:5px;font-size:8px">Consumo: acabamento ${c.finishCalc?.consumption.toFixed(2)||0}m; forro ${c.liningCalc?.consumption.toFixed(2)||0}m; laterais ${c.lateral.toFixed(2)}m; barras ${c.bars.toFixed(2)}m; costura ${c.sewingMeters.toFixed(2)}m; deslizantes ${c.finishSliders+c.liningSliders} un; ${esc(c.fixationCalc.detail)}.</div>`});$('view-quote').classList.add('print-target');window.print();setTimeout(()=>$('view-quote').classList.remove('print-target'),300)}

function renderQuotes(){const tb=$('quotesTable');if(!tb)return;const q=norm($('quoteSearch')?.value);const converted=new Set(db.orders.map(o=>Number(o.quoteNumber)));tb.innerHTML='';for(const x of db.quotes.filter(canSeeQuote).filter(x=>!q||norm(`${x.numero} ${x.client} ${x.seller}`).includes(q))){const t=quoteTotals(x),conv=converted.has(Number(x.numero));const tr=document.createElement('tr');tr.innerHTML=`<td>${String(x.numero).padStart(6,'0')}</td><td>${fmtDate(x.date)}</td><td>${esc(x.client)}</td><td>${esc(x.seller)}</td><td>${x.environments?.length||0}</td><td>${money(t.cash)}</td><td><span class="badge ${conv?'blue':'ok'}">${conv?'PEDIDO':'ORÇAMENTO'}</span></td><td><div class="actions"><button class="btn ghost" data-q-load="${x.numero}">Abrir</button><button class="btn ghost" data-q-print="${x.numero}">PDF</button>${conv?`<button class="btn danger" data-q-revert="${x.numero}">Reverter</button>`:`<button class="btn primary" data-q-convert="${x.numero}">Converter</button>`}</div></td>`;tb.appendChild(tr)}bindQuoteActions()}
function bindQuoteActions(){document.querySelectorAll('[data-q-load]').forEach(b=>b.onclick=()=>{const q=db.quotes.find(x=>Number(x.numero)===Number(b.dataset.qLoad));if(q){draft=clone(q);renderQuote();setView('quote')}});document.querySelectorAll('[data-q-print]').forEach(b=>b.onclick=()=>{const q=db.quotes.find(x=>Number(x.numero)===Number(b.dataset.qPrint));if(q)openPrintChoice(q)});document.querySelectorAll('[data-q-convert]').forEach(b=>b.onclick=()=>convertQuote(Number(b.dataset.qConvert)));document.querySelectorAll('[data-q-revert]').forEach(b=>b.onclick=()=>revertQuote(Number(b.dataset.qRevert)))}
function openPrintChoice(q){openModal(`<h2>Imprimir orçamento ${String(q.numero).padStart(6,'0')}</h2><p>Escolha o modelo.</p><div class="actions"><button id="printSummary" class="btn primary">Orçamento resumido</button><button id="printDetail" class="btn secondary">Orçamento detalhado</button></div>`);$('printSummary').onclick=()=>{closeModal();printQuote(q,'summary')};$('printDetail').onclick=()=>{closeModal();printQuote(q,'detail')}}
function convertQuote(n){const q=db.quotes.find(x=>Number(x.numero)===n);if(!q)return;const t=quoteTotals(q);openModal(`<h2>Converter em pedido</h2><div class="grid two"><label class="field">Condição<select id="convCond"><option value="cash">À vista</option><option value="p4">Até 4x</option><option value="p18">Até 18x</option></select></label><label class="field">Data de instalação / entrega<input id="convDate" type="date"></label><label class="field">Desconto adicional (%)<input id="convDiscount" type="number" min="0" max="100" value="0"></label><label class="field">Justificativa<input id="convReason"></label></div><p class="muted">À vista ${money(t.cash)} • 4x ${money(t.p4)} • 18x ${money(t.p18)}</p><button id="convGo" class="btn primary">Gerar pedido</button>`);$('convGo').onclick=()=>{const cond=$('convCond').value,date=$('convDate').value,disc=Number($('convDiscount').value||0),reason=$('convReason').value.trim();if(!date)return alert('Informe a data.');if(disc>0&&!reason)return alert('Justifique o desconto.');const base=cond==='cash'?t.cash:cond==='p18'?t.p18:t.p4;const order={id:uid(),numero:nextOrderNumber(),quoteNumber:q.numero,ownerUser:q.ownerUser||currentUsername(),client:q.client,address:q.address,contact:q.contact,seller:q.seller,environments:clone(q.environments),createdDate:today(),deliveryDate:date,paymentCondition:cond,originalValue:base,discountPercent:disc,discountReason:reason,agreedValue:base*(1-disc/100),productionStage:'RECEPÇÃO',productionHistory:[{stage:'RECEPÇÃO',at:new Date().toISOString(),by:currentUsername()}],installation:{responsible:'',completedDate:''},payments:[],createdAt:new Date().toISOString()};db.orders.unshift(order);q.status='PEDIDO';queueSave();closeModal();renderAll();setView('orders')}}
function revertQuote(n){const idx=db.orders.findIndex(o=>Number(o.quoteNumber)===n);if(idx<0)return;if(!isGestor()&&!confirm('Reverter este pedido para orçamento?'))return;if(isGestor()&&!confirm('Excluir o pedido vinculado e retornar o orçamento ao status ORÇAMENTO?'))return;db.orders.splice(idx,1);const q=db.quotes.find(x=>Number(x.numero)===n);if(q)q.status='ORÇAMENTO';queueSave();renderAll()}

function renderClients(){const tb=$('clientsTable');if(!tb)return;const s=norm($('clientSearch')?.value);tb.innerHTML='';for(const c of db.clients.filter(c=>!s||norm(`${c.name} ${c.contact} ${c.address}`).includes(s))){const tr=document.createElement('tr');tr.innerHTML=`<td>${esc(c.name)}</td><td>${esc(c.contact||'-')}</td><td>${esc(c.address||'-')}</td><td>${esc(c.lastSeller||'-')}</td><td><button class="btn ghost" data-client-edit="${c.id}">Editar</button> <button class="btn danger" data-client-del="${c.id}">Excluir</button></td>`;tb.appendChild(tr)}document.querySelectorAll('[data-client-edit]').forEach(b=>b.onclick=()=>openClientModal(db.clients.find(c=>c.id===b.dataset.clientEdit)));document.querySelectorAll('[data-client-del]').forEach(b=>b.onclick=()=>{if(confirm('Excluir este cliente?')){db.clients=db.clients.filter(c=>c.id!==b.dataset.clientDel);queueSave();renderClients()}})}
function openClientModal(c=null){editingClientId=c?.id||null;openModal(`<h2>${c?'Editar':'Novo'} cliente</h2><div class="grid two"><label class="field">Nome<input id="mClientName" value="${esc(c?.name||'')}"></label><label class="field">Contato<input id="mClientContact" value="${esc(c?.contact||'')}"></label><label class="field" style="grid-column:1/-1">Endereço<input id="mClientAddress" value="${esc(c?.address||'')}"></label></div><button id="mClientSave" class="btn primary">Salvar</button>`);$('mClientSave').onclick=()=>{const name=$('mClientName').value.trim();if(!name)return alert('Informe o nome.');const obj={id:editingClientId||uid(),name,contact:$('mClientContact').value.trim(),address:$('mClientAddress').value.trim(),lastSeller:c?.lastSeller||sellerName(currentUser?.username),updatedAt:new Date().toISOString()};if(editingClientId){const i=db.clients.findIndex(x=>x.id===editingClientId);db.clients[i]={...db.clients[i],...obj}}else db.clients.unshift(obj);queueSave();closeModal();renderClients()}}

function renderOrders(){const tb=$('ordersTable');if(!tb)return;tb.innerHTML='';for(const o of db.orders.filter(canSeeOrder)){const install=o.installation?.completedDate?'CONCLUÍDA':o.productionStage==='EXPEDIÇÃO'?'PRONTO PARA INSTALAÇÃO':'AGUARDANDO';const tr=document.createElement('tr');tr.innerHTML=`<td>${String(o.numero).padStart(6,'0')}</td><td>${String(o.quoteNumber).padStart(6,'0')}</td><td>${esc(o.client)}</td><td>${esc(o.seller)}</td><td>${money(o.agreedValue)}</td><td><span class="badge blue">${esc(o.productionStage||'RECEPÇÃO')}</span></td><td><span class="badge ${install==='CONCLUÍDA'?'ok':'warn'}">${install}</span></td><td><button class="btn ghost" data-order-open="${o.numero}">Abrir</button></td>`;tb.appendChild(tr)}document.querySelectorAll('[data-order-open]').forEach(b=>b.onclick=()=>openOrder(Number(b.dataset.orderOpen)))}
function openOrder(n){const o=db.orders.find(x=>Number(x.numero)===n);if(!o)return;const paid=(o.payments||[]).reduce((a,p)=>a+Number(p.value||0),0);openModal(`<h2>Pedido ${String(o.numero).padStart(6,'0')}</h2><div class="detail-list"><div class="detail-item"><span>Cliente</span><strong>${esc(o.client)}</strong></div><div class="detail-item"><span>Valor</span><strong>${money(o.agreedValue)}</strong></div><div class="detail-item"><span>Saldo</span><strong>${money(o.agreedValue-paid)}</strong></div><div class="detail-item"><span>Produção</span><strong>${esc(o.productionStage)}</strong></div><div class="detail-item"><span>Entrega</span><strong>${fmtDate(o.deliveryDate)}</strong></div><div class="detail-item"><span>Comissão</span><strong>${money(o.agreedValue*sellerCommission(o.ownerUser||o.seller)/100)}</strong></div></div><h3>Pagamento</h3><div class="grid two"><label class="field">Valor<input id="payVal" type="number" min="0" step="0.01"></label><label class="field">Data<input id="payDate" type="date" value="${today()}"></label></div><div class="actions" style="margin-top:10px"><button id="addPay" class="btn primary">Adicionar pagamento</button><button id="printOS" class="btn secondary">Imprimir OS de produção</button></div>`);$('addPay').onclick=()=>{const v=Number($('payVal').value),d=$('payDate').value;if(!v||!d)return alert('Informe valor e data.');o.payments=o.payments||[];o.payments.push({value:v,date:d,by:currentUsername(),at:new Date().toISOString()});queueSave();closeModal();renderOrders()};$('printOS').onclick=()=>{closeModal();printProductionOrder(o)}}
function printProductionOrder(o){const old=draft;draft={numero:o.quoteNumber,client:o.client,date:o.createdDate,address:o.address,contact:o.contact,seller:o.seller,travel:0,environments:clone(o.environments)};renderQuote();$('printQuoteTitle').textContent=`ORDEM DE PRODUÇÃO • PEDIDO ${String(o.numero).padStart(6,'0')}`;document.querySelectorAll('#envTable tr').forEach((tr,i)=>{const e=o.environments[i],c=e&&calcEnvironment(e);if(!c)return;tr.cells[0].innerHTML+=`<div class="print-only" style="font-size:8px">CORTE: acabamento ${c.finishCalc?.consumption.toFixed(2)||0}m; forro ${c.liningCalc?.consumption.toFixed(2)||0}m; ${c.finishCalc?.panels||0} / ${c.liningCalc?.panels||0} alturas; costura ${c.sewingMeters.toFixed(2)}m; deslizantes ${c.finishSliders+c.liningSliders}; ${esc(c.fixationCalc.detail)}.</div>`});$('view-quote').classList.add('print-target');window.print();setTimeout(()=>{draft=old;renderQuote();$('view-quote').classList.remove('print-target')},300)}

function renderProduction(){const box=$('productionList');if(!box)return;box.innerHTML='';for(const o of db.orders){const c=document.createElement('div');c.className='card';c.innerHTML=`<div class="card-title">Pedido ${String(o.numero).padStart(6,'0')} • ${esc(o.client)}</div><div class="stage-row">${STAGES.map(s=>`<button class="stage ${o.productionStage===s?'active':''}" data-stage-order="${o.numero}" data-stage="${s}">${s}</button>`).join('')}</div><p class="muted">Entrega: ${fmtDate(o.deliveryDate)} • ${o.environments?.length||0} ambiente(s). ${o.productionStage==='EXPEDIÇÃO'?'<strong>PEDIDO PRONTO PARA INSTALAÇÃO</strong>':''}</p>`;box.appendChild(c)}document.querySelectorAll('[data-stage-order]').forEach(b=>b.onclick=()=>{const o=db.orders.find(x=>Number(x.numero)===Number(b.dataset.stageOrder));if(!o)return;o.productionStage=b.dataset.stage;o.productionHistory=o.productionHistory||[];o.productionHistory.push({stage:b.dataset.stage,at:new Date().toISOString(),by:currentUsername()});queueSave();renderProduction();renderOrders();renderInstall()})}
function renderInstall(){const tb=$('installTable');if(!tb)return;tb.innerHTML='';for(const o of db.orders.slice().sort((a,b)=>String(a.deliveryDate).localeCompare(String(b.deliveryDate)))){const ready=o.productionStage==='EXPEDIÇÃO',done=!!o.installation?.completedDate;const tr=document.createElement('tr');tr.innerHTML=`<td>${fmtDate(o.deliveryDate)}</td><td>${String(o.numero).padStart(6,'0')}</td><td>${esc(o.client)}</td><td>${esc(o.productionStage)}</td><td><span class="badge ${done?'ok':ready?'blue':'warn'}">${done?'INSTALADO':ready?'PRONTO PARA INSTALAÇÃO':'EM PRODUÇÃO'}</span></td><td>${esc(o.installation?.responsible||'-')} ${ready&&!done?`<button class="btn ghost" data-install="${o.numero}">Atualizar</button>`:''}</td>`;tb.appendChild(tr)}document.querySelectorAll('[data-install]').forEach(b=>b.onclick=()=>openInstall(Number(b.dataset.install)))}
function openInstall(n){const o=db.orders.find(x=>Number(x.numero)===n);openModal(`<h2>Instalação • Pedido ${String(n).padStart(6,'0')}</h2><div class="grid two"><label class="field">Responsável<input id="instResp" value="${esc(o.installation?.responsible||'')}"></label><label class="field">Data concluída<input id="instDate" type="date" value="${o.installation?.completedDate||''}"></label></div><button id="instSave" class="btn primary">Salvar</button>`);$('instSave').onclick=()=>{o.installation={...(o.installation||{}),responsible:$('instResp').value.trim(),completedDate:$('instDate').value};queueSave();closeModal();renderInstall();renderOrders()}}

function productPrices(p){const base=Number(p.cost||0)*(1+Number(p.markup||0)/100);return {p4:base,p18:base*(1+db.priceConfig.terms.p18AddPct/100),cash:base*(1-db.priceConfig.terms.cashDiscountPct/100)}}
function renderProducts(){const tb=$('productsTable');if(!tb)return;const s=norm($('productSearch')?.value);tb.innerHTML='';for(const p of db.products.filter(p=>!s||norm(`${p.type} ${p.category} ${p.name} ${p.color}`).includes(s))){const pr=productPrices(p),tr=document.createElement('tr');tr.innerHTML=`<td>${esc(p.type)}</td><td>${esc(p.category)}</td><td>${esc(p.name)}</td><td>${esc(p.color)}</td><td>${Number(p.qty||0)}</td><td>${money(p.cost)}</td><td>${Number(p.markup||0)}%</td><td>${money(pr.p18)}</td><td>${money(pr.p4)}</td><td>${money(pr.cash)}</td><td><button class="btn ghost" data-prod-edit="${p.id}">Editar</button> <button class="btn danger" data-prod-del="${p.id}">Excluir</button></td>`;tb.appendChild(tr)}document.querySelectorAll('[data-prod-edit]').forEach(b=>b.onclick=()=>openProduct(db.products.find(x=>x.id===b.dataset.prodEdit)));document.querySelectorAll('[data-prod-del]').forEach(b=>b.onclick=()=>{if(confirm('Excluir produto?')){db.products=db.products.filter(x=>x.id!==b.dataset.prodDel);queueSave();renderProducts()}})}
function openProduct(p=null){openModal(`<h2>${p?'Editar':'Novo'} produto</h2><div class="grid two"><label class="field">Tipo<select id="pType"><option>TECIDO DE ACABAMENTO</option><option>TECIDO DE FORRO</option><option>ACESSÓRIOS</option><option>AVIAMENTO</option><option>OUTRO</option></select></label><label class="field">Categoria<input id="pCat" value="${esc(p?.category||'')}"></label><label class="field">Nome<input id="pName" value="${esc(p?.name||'')}"></label><label class="field">Cor<input id="pColor" value="${esc(p?.color||'')}"></label><label class="field">Quantidade<input id="pQty" type="number" step="0.01" value="${Number(p?.qty||0)}"></label><label class="field">Custo de compra<input id="pCost" type="number" step="0.01" value="${Number(p?.cost||0)}"></label><label class="field">Markup (%)<input id="pMarkup" type="number" step="0.01" value="${Number(p?.markup||80)}"></label></div><button id="pSave" class="btn primary">Salvar</button>`);if(p)$('pType').value=p.type;$('pSave').onclick=()=>{const obj={id:p?.id||uid(),type:$('pType').value,category:$('pCat').value.trim(),name:$('pName').value.trim(),color:$('pColor').value.trim(),qty:Number($('pQty').value||0),cost:Number($('pCost').value||0),markup:Number($('pMarkup').value||0)};if(!obj.name)return alert('Informe o produto.');const i=db.products.findIndex(x=>x.id===obj.id);if(i>=0)db.products[i]=obj;else db.products.unshift(obj);queueSave();closeModal();renderProducts()}}

function renderPricing(){const root=$('pricingForm');if(!root)return;const c=db.priceConfig;root.innerHTML=`<div class="grid two"><section class="card"><div class="card-title">Tecidos de acabamento</div>${Object.entries(c.finishes).map(([n,v])=>priceRow('finish',n,v.price)).join('')}</section><section class="card"><div class="card-title">Tecidos de forro</div>${Object.entries(c.linings).map(([n,v])=>priceRow('lining',n,v.price)).join('')}</section><section class="card"><div class="card-title">Mão de obra e aviamentos</div>${numField('sewing','Costura por metro',c.sewingPerMeter)}${numField('sliderFinish','Deslizante acabamento',c.sliders.finish)}${numField('sliderLining','Deslizante forro',c.sliders.lining)}${numField('swissClamp','Garra trilho suíço',c.swiss.clamp)}${numField('swissEnd','Acabamento trilho suíço',c.swiss.end)}${numField('waveMeter','Varão Wave / metro',c.wave.rodPerMeter)}${numField('waveSupport','Suporte Wave',c.wave.support)}${numField('waveEnd','Tampa Wave (não informada no documento)',c.wave.end)}</section><section class="card"><div class="card-title">Condições e automação</div>${numField('cashPct','Desconto à vista (%)',c.terms.cashDiscountPct)}${numField('p18Pct','Acréscimo 18x (%)',c.terms.p18AddPct)}${numField('cordPct','Comando por corda (%)',c.cordPct)}${numField('motorBase','Motor por folha',c.motor.basePerLeaf)}${numField('motorPct','Acréscimo ferragens motor (%)',c.motor.hardwarePct)}${numField('commDefault','Comissão padrão (%)',c.commissionDefault)}</section></div><section class="card" style="margin-top:14px"><div class="card-title">Instalação por altura</div><div class="grid four">${c.install.map((x,i)=>`<label class="field">Até ${x.maxH>=99?'acima de 6':x.maxH}m<input data-install-price="${i}" type="number" step="0.01" value="${x.price}"></label>`).join('')}</div></section>`}
function priceRow(kind,name,val){return `<label class="field" style="margin:8px 0">${esc(name)} (R$/m)<input data-price-kind="${kind}" data-price-name="${esc(name)}" type="number" step="0.01" value="${val}"></label>`}
function numField(id,label,val){return `<label class="field" style="margin:8px 0">${label}<input id="price-${id}" type="number" step="0.01" value="${val}"></label>`}
function savePricing(){document.querySelectorAll('[data-price-kind]').forEach(i=>{const k=i.dataset.priceKind,n=i.dataset.priceName,v=Number(i.value||0);if(k==='finish')db.priceConfig.finishes[n].price=v;else db.priceConfig.linings[n].price=v});db.priceConfig.sewingPerMeter=Number($('price-sewing').value);db.priceConfig.sliders.finish=Number($('price-sliderFinish').value);db.priceConfig.sliders.lining=Number($('price-sliderLining').value);db.priceConfig.swiss.clamp=Number($('price-swissClamp').value);db.priceConfig.swiss.end=Number($('price-swissEnd').value);db.priceConfig.wave.rodPerMeter=Number($('price-waveMeter').value);db.priceConfig.wave.support=Number($('price-waveSupport').value);db.priceConfig.wave.end=Number($('price-waveEnd').value);db.priceConfig.terms.cashDiscountPct=Number($('price-cashPct').value);db.priceConfig.terms.p18AddPct=Number($('price-p18Pct').value);db.priceConfig.cordPct=Number($('price-cordPct').value);db.priceConfig.motor.basePerLeaf=Number($('price-motorBase').value);db.priceConfig.motor.hardwarePct=Number($('price-motorPct').value);db.priceConfig.commissionDefault=Number($('price-commDefault').value);document.querySelectorAll('[data-install-price]').forEach(i=>db.priceConfig.install[Number(i.dataset.installPrice)].price=Number(i.value||0));queueSave();setupSelectors();renderAll();alert('Tabela de preços atualizada.')}

function renderKpis(){const cards=$('kpiCards'),seller=$('sellerKpis');if(!cards)return;const quotes=db.quotes.length,orders=db.orders.length,revenue=db.orders.reduce((a,o)=>a+Number(o.agreedValue||0),0),paid=db.orders.reduce((a,o)=>a+(o.payments||[]).reduce((s,p)=>s+Number(p.value||0),0),0),ticket=orders?revenue/orders:0,conversion=quotes?orders/quotes*100:0,reworks=db.reworks.length;cards.innerHTML=[['Clientes atendidos',db.clients.length],['Pedidos efetivados',orders],['Saldo a receber',money(Math.max(0,revenue-paid))],['Conversão',conversion.toFixed(1)+'%'],['Ticket médio',money(ticket)],['Faturamento',money(revenue)],['Retrabalhos',reworks],['Em produção',db.orders.filter(o=>o.productionStage!=='EXPEDIÇÃO').length]].map(x=>`<div class="kpi"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');const by={};for(const o of db.orders){const k=o.seller||o.ownerUser||'-';by[k]??={count:0,total:0};by[k].count++;by[k].total+=Number(o.agreedValue||0)}seller.innerHTML=Object.entries(by).map(([k,v])=>`<div class="detail-item" style="margin:6px 0"><span>${esc(k)}</span><strong>${v.count} pedido(s) • ${money(v.total)} • Comissão estimada ${money(v.total*sellerCommission(k)/100)}</strong></div>`).join('')||'<p class="muted">Ainda não há pedidos.</p>'}

function renderPayables(){const tb=$('payablesTable');if(!tb)return;tb.innerHTML='';for(const p of db.payables){const tr=document.createElement('tr');tr.innerHTML=`<td>${esc(p.title)}</td><td>${esc(p.definition)}</td><td>${esc(p.quoteNumber||'-')}</td><td>${fmtDate(p.dueDate)}</td><td>${money(p.value)}</td><td>${money(p.paidValue)}</td><td>${fmtDate(p.paidDate)}</td><td><button class="btn ghost" data-payable-edit="${p.id}">Editar</button></td>`;tb.appendChild(tr)}document.querySelectorAll('[data-payable-edit]').forEach(b=>b.onclick=()=>openPayable(db.payables.find(x=>x.id===b.dataset.payableEdit)))}
function openPayable(p=null){openModal(`<h2>${p?'Editar':'Novo'} título</h2><div class="grid two"><label class="field">Nome do título<input id="apTitle" value="${esc(p?.title||'')}"></label><label class="field">Definição<input id="apDef" value="${esc(p?.definition||'')}"></label><label class="field">Nº orçamento<input id="apQuote" value="${esc(p?.quoteNumber||'')}"></label><label class="field">Vencimento<input id="apDue" type="date" value="${p?.dueDate||''}"></label><label class="field">Valor<input id="apValue" type="number" step="0.01" value="${Number(p?.value||0)}"></label><label class="field">Valor pago<input id="apPaid" type="number" step="0.01" value="${Number(p?.paidValue||0)}"></label><label class="field">Data pagamento<input id="apPaidDate" type="date" value="${p?.paidDate||''}"></label><label class="field">Observações<textarea id="apNotes">${esc(p?.notes||'')}</textarea></label></div><button id="apSave" class="btn primary">Salvar</button>`);$('apSave').onclick=()=>{const obj={id:p?.id||uid(),title:$('apTitle').value.trim(),definition:$('apDef').value.trim(),quoteNumber:$('apQuote').value.trim(),dueDate:$('apDue').value,value:Number($('apValue').value||0),paidValue:Number($('apPaid').value||0),paidDate:$('apPaidDate').value,notes:$('apNotes').value.trim()};if(!obj.title)return alert('Informe o título.');const i=db.payables.findIndex(x=>x.id===obj.id);if(i>=0)db.payables[i]=obj;else db.payables.unshift(obj);queueSave();closeModal();renderPayables()}}

function renderSuppliers(){const root=$('supplierList');if(!root)return;root.innerHTML='';for(const s of db.suppliers){const c=document.createElement('div');c.className='card';c.innerHTML=`<div class="card-title">${esc(s.name)}</div><p><strong>Contato:</strong> ${esc(s.contact||'-')}</p><p><strong>Tipo:</strong> ${esc(s.productType||'-')}</p><p><strong>Condição:</strong> ${esc(s.condition||'-')}</p><p><strong>Prazo médio:</strong> ${Number(s.avgDays||0)} dias</p><button class="btn ghost" data-sup-edit="${s.id}">Editar</button>`;root.appendChild(c)}document.querySelectorAll('[data-sup-edit]').forEach(b=>b.onclick=()=>openSupplier(db.suppliers.find(x=>x.id===b.dataset.supEdit)))}
function openSupplier(s=null){openModal(`<h2>${s?'Editar':'Novo'} fornecedor</h2><div class="grid two"><label class="field">Fornecedor<input id="supName" value="${esc(s?.name||'')}"></label><label class="field">Responsável / contato<input id="supContact" value="${esc(s?.contact||'')}"></label><label class="field">Tipo de produto<input id="supType" value="${esc(s?.productType||'')}"></label><label class="field">Condição de venda<input id="supCond" value="${esc(s?.condition||'')}"></label><label class="field">Prazo médio entrega (dias)<input id="supDays" type="number" value="${Number(s?.avgDays||0)}"></label><label class="field">Observações<textarea id="supNotes">${esc(s?.notes||'')}</textarea></label></div><button id="supSave" class="btn primary">Salvar</button>`);$('supSave').onclick=()=>{const obj={id:s?.id||uid(),name:$('supName').value.trim(),contact:$('supContact').value.trim(),productType:$('supType').value.trim(),condition:$('supCond').value.trim(),avgDays:Number($('supDays').value||0),notes:$('supNotes').value.trim()};if(!obj.name)return alert('Informe o fornecedor.');const i=db.suppliers.findIndex(x=>x.id===obj.id);if(i>=0)db.suppliers[i]=obj;else db.suppliers.unshift(obj);queueSave();closeModal();renderSuppliers()}}

function renderReworks(){const tb=$('reworksTable');if(!tb)return;tb.innerHTML='';for(const r of db.reworks){const tr=document.createElement('tr');tr.innerHTML=`<td>${esc(r.number)}</td><td>${esc(r.orderNumber)}</td><td>${fmtDate(r.date)}</td><td>${esc(r.summary)}</td><td><span class="badge warn">${esc(r.status)}</span></td>`;tb.appendChild(tr)}}
function openRework(){openModal(`<h2>Novo retrabalho</h2><div class="grid two"><label class="field">Pedido<input id="rwOrder"></label><label class="field">Data<input id="rwDate" type="date" value="${today()}"></label><label class="field" style="grid-column:1/-1">Resumo<textarea id="rwSummary"></textarea></label></div><button id="rwSave" class="btn primary">Salvar</button>`);$('rwSave').onclick=()=>{const order=$('rwOrder').value.trim(),summary=$('rwSummary').value.trim();if(!order||!summary)return alert('Informe pedido e resumo.');db.reworks.unshift({id:uid(),number:`RT-${String(db.reworks.length+1).padStart(4,'0')}`,orderNumber:order,date:$('rwDate').value,summary,status:'ABERTO'});queueSave();closeModal();renderReworks()}}

function renderUsers(){const tb=$('usersTable');if(!tb)return;const disabled=new Set((db.disabledUsers||[]).map(norm));tb.innerHTML='';for(const u of [...DEFAULT_USERS,...db.users].filter((u,i,a)=>a.findIndex(x=>norm(x.username)===norm(u.username))===i)){const dis=disabled.has(norm(u.username));const tr=document.createElement('tr');tr.innerHTML=`<td>${esc(u.username)}</td><td>${esc(u.name||'-')}</td><td>${esc(u.role)}</td><td>${Number(u.commission||0)}%</td><td>${esc(u.createdBy|| (u.builtIn?'SISTEMA':'-'))}</td><td>${u.createdAt?fmtDate(u.createdAt.slice(0,10)):'-'}</td><td><span class="badge ${dis?'danger':'ok'}">${dis?'DESATIVADO':'ATIVO'}</span></td>`;tb.appendChild(tr)}}
function openUser(){openModal(`<h2>Novo usuário</h2><div class="grid two"><label class="field">Usuário<input id="uUser"></label><label class="field">Nome completo<input id="uName"></label><label class="field">Senha<input id="uPass" type="password"></label><label class="field">Perfil<select id="uRole"><option value="sales">VENDAS</option><option value="production">PRODUÇÃO</option><option value="gestor">GESTOR</option></select></label><label class="field">Comissão (%)<input id="uComm" type="number" value="${db.priceConfig.commissionDefault||5}"></label></div><div class="notice" style="margin:10px 0">O usuário é registrado com o gestor responsável e a data de inclusão.</div><button id="uSave" class="btn primary">Criar usuário</button>`);$('uSave').onclick=async()=>{const username=norm($('uUser').value),name=$('uName').value.trim(),pass=$('uPass').value,role=$('uRole').value;if(username.length<3||pass.length<6)return alert('Usuário deve ter 3+ caracteres e senha 6+ caracteres.');if(allUsers().some(x=>norm(x.username)===username))return alert('Usuário já existe.');db.users.push({username,name,role,commission:Number($('uComm').value||0),hash:await sha256(pass),builtIn:false,createdBy:currentUsername(),createdAt:new Date().toISOString(),permissions:role==='gestor'?['*']:role==='production'?['production','orders','install']:['quote','quotes','clients','orders','install']});queueSave();closeModal();renderUsers()}}

function openModal(html){$('modalBody').innerHTML=html;$('modal').classList.add('open')}function closeModal(){$('modal').classList.remove('open');$('modalBody').innerHTML=''}

async function doLogin(){const user=norm($('loginUser').value),pass=$('loginPass').value;if(!user||!pass)return $('loginError').textContent='Informe usuário e senha.';try{$('loginBtn').disabled=true;$('loginError').textContent='';const j=await api('auth',{method:'POST',body:JSON.stringify({username:user,passwordHash:await sha256(pass)})});token=j.token;currentUser={username:j.username,role:j.role,name:j.name};sessionStorage.setItem('novaV8Token',token);sessionStorage.setItem('novaV8User',JSON.stringify(currentUser));document.body.classList.remove('auth-locked');$('loginScreen').classList.add('hidden');$('sessionUser').textContent=`${j.name||j.username} • ${String(j.role).toUpperCase()}`;draft.seller=sellerName(j.username);await loadCloud();setupSelectors();renderQuote()}catch(e){$('loginError').textContent=e.message}finally{$('loginBtn').disabled=false}}
function logout(){sessionStorage.removeItem('novaV8Token');sessionStorage.removeItem('novaV8User');location.reload()}
async function restore(){if(!token||!currentUser)return false;try{await api('data');document.body.classList.remove('auth-locked');$('loginScreen').classList.add('hidden');$('sessionUser').textContent=`${currentUser.name||currentUser.username} • ${String(currentUser.role).toUpperCase()}`;await loadCloud();setupSelectors();return true}catch{token='';currentUser=null;sessionStorage.clear();return false}}

function bind(){document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{$('eModel').value=b.dataset.model;updateModelFields()});['eName','eWidth','eHeight','eLeaves','eFinish','eFinishColor','eFinishPleat','eFinishGather','eLining','eLiningColor','eLiningPleat','eLiningGather','eFixation','eFixColor','eCustomPleat'].forEach(id=>$(id).addEventListener('input',updatePreview));$('addEnvBtn').onclick=()=>{const e=envFromForm();if(!e.name||!e.width||!e.height)return alert('Preencha ambiente, largura e altura.');draft.environments.push(e);renderQuote();clearEnv()};['qClient','qDate','qAddress','qContact','qSeller'].forEach(id=>$(id).addEventListener('input',syncDraft));$('qTravel').addEventListener('input',()=>{syncDraft();renderQuote()});$('saveQuoteBtn').onclick=()=>saveQuote(false);$('savePrintBtn').onclick=()=>saveQuote(true);$('resetQuoteBtn').onclick=resetQuote;$('quoteSearch').addEventListener('input',renderQuotes);$('clientSearch').addEventListener('input',renderClients);$('productSearch').addEventListener('input',renderProducts);$('newClientBtn').onclick=()=>openClientModal();$('newProductBtn').onclick=()=>openProduct();$('savePricesBtn').onclick=savePricing;$('newPayableBtn').onclick=()=>openPayable();$('newSupplierBtn').onclick=()=>openSupplier();$('newReworkBtn').onclick=openRework;$('newUserBtn').onclick=openUser;$('modalClose').onclick=closeModal;$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeModal()});$('loginBtn').onclick=doLogin;$('loginPass').addEventListener('keydown',e=>{if(e.key==='Enter')doLogin()});$('logoutBtn').onclick=logout}

async function init(){bind();db.priceConfig=mergeConfig(db.priceConfig);setupSelectors();draft.seller='';renderQuote();if(!await restore()){$('loginScreen').classList.remove('hidden');setTimeout(()=>$('loginUser').focus(),50)}}
init();
